version: "3.9"
services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
